version: '{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
configuration:
  - Release
services:
- postgresql
before_build:
  - cmd: dotnet --version
build_script:
  - cmd: dotnet build .
test_script:
  - cmd: dotnet test .
environment:
  postgres_connection:
    secure: YW0OmwTb/Q3byjNiJzsXc4UN5JJRbI3uYItkJPLB3F1vGKkwyR8d3VzpAxYldjhp3PZCRzF8aoUNMrlz5GJXazO7KGxas4YWXP7OirDBibEC6Pn4MZM0XECIHWTkmUCc8mLa6sZRsWXcG5t+NRXa2w==