version: '{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
configuration:
  - Release
services:
- postgresql
before_build:
  - cmd: dotnet --version
  - cmd: echo %postgres_connection%
build_script:
  - cmd: dotnet build .
test_script:
  - cmd: dotnet test .
environment:
  postgres_connection:
    secure: YW0OmwTb/Q3byjNiJzsXc4UN5JJRbI3uYItkJPLB3F2d/rxamWDJbfwQ7aI0FEfQ6YYPoafFf4Of9o0bYo1ls8w8DzT1xx9RIBZ5nSdnUR9yFIHo2imYYHD+w+4JMGHh
    